baseURL: http://localhost:1313

languageCode: en-us
title: "Fred's Blog"
# defaultContentLanguage: fr

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 2
