baseURL: http://localhost:1313

languageCode: en-us
title: "Fred's Blog"
theme: "toha"
defaultContentLanguage: fr

languages:
  fr:
    languageName: Français
    weight: 1
  en:
    languageName: English
    weight: 2
