name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hugoweb:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Inspect
      run: |
        docker image inspect myimage:latest

    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
