name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: hugoweb
  IMAGE_TAG: latest

jobs:

  lint:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: get-version
      run: echo "::set-output name=version::$(cat VERSION)"
      
#   job2:
#     runs-on: ubuntu-latest

#     steps:
#     - run: echo ${{needs.lint.outputs.version}}

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ env.IMAGE_NAME }}:${{needs.lint.outputs.version}}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Inspect
      run: |
        docker image inspect ${{ env.IMAGE_NAME }}:${{needs.lint.outputs.version}}
    
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
